# Generated by Django 2.1 on 2018-08-18 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subproduto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsula',
            name='subProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsulas', to='core.SubProduto'),
        ),
        migrations.AlterField(
            model_name='subproduto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprodutos', to='core.Projeto'),
        ),
    ]
