# Generated by Django 2.1 on 2018-08-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180818_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
            preserve_default=False,
        ),
    ]
