# Generated by Django 2.1 on 2018-08-19 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recurso_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.Projeto'),
        ),
    ]
