# Generated by Django 2.0.5 on 2018-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180819_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsula',
            name='recursos',
            field=models.ManyToManyField(null=True, to='core.Recurso'),
        ),
    ]
