# Generated by Django 2.1 on 2018-08-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180819_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='capsula_ativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Capsula'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
