# Generated by Django 2.1 on 2018-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180819_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsula',
            name='ativacao',
            field=models.DateTimeField(null=True),
        ),
    ]
